import { LegalLayout } from '@/components/legal/LegalLayout';

export default function PrivacyPage() {
	const sections = [
		{
			id: "intro",
			title: "Introduction",
			content: (
				<>
					<p>
						At Volteryde, we regard the privacy of your data as a critical infrastructure component.
						This Privacy Policy outlines the protocols we employ to collect, encrypt, and manage data
						generated by your fleet and interactions with our platform.
					</p>
					<p>
						By accessing the Volteryde grid services, you consent to the data practices described in this statement.
					</p>
				</>
			)
		},
		{
			id: "data-collection",
			title: "Data Collection",
			content: (
				<>
					<p>We collect telemetry data directly from connected vehicles and charging infrastructure, including:</p>
					<ul className="list-disc pl-4 space-y-2 marker:text-neon">
						<li>State of Charge (SoC) and battery health metrics.</li>
						<li>GPS location data for route optimization.</li>
						<li>Charging session duration and energy consumption (kWh).</li>
						<li>Device diagnostics and firmware versions.</li>
					</ul>
				</>
			)
		},
		{
			id: "usage",
			title: "Data Usage",
			content: (
				<p>
					The collected data is processed to deliver our core services: predictive maintenance,
					route planning, and automated V2G (Vehicle-to-Grid) energy trading. We do not sell
					your raw fleet data to third-party data brokers.
				</p>
			)
		},
		{
			id: "security",
			title: "Security Protocols",
			content: (
				<p>
					All data in transit is encrypted using TLS 1.3. Data at rest is secured with AES-256 encryption.
					Access to sensitive fleet data is strictly controlled via Role-Based Access Control (RBAC)
					and Multi-Factor Authentication (MFA).
				</p>
			)
		}
	];

	return (
		<LegalLayout
			title="Privacy Policy"
			lastUpdated="December 12, 2025"
			sections={sections}
		/>
	);
}
